// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: proto/rampaz.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	K8SInfo_ListPods_FullMethodName             = "/k8sinfo.K8sInfo/ListPods"
	K8SInfo_GetNodeStats_FullMethodName         = "/k8sinfo.K8sInfo/GetNodeStats"
	K8SInfo_GetPodStats_FullMethodName          = "/k8sinfo.K8sInfo/GetPodStats"
	K8SInfo_GetNodeRealTimeStats_FullMethodName = "/k8sinfo.K8sInfo/GetNodeRealTimeStats"
	K8SInfo_StreamEvents_FullMethodName         = "/k8sinfo.K8sInfo/StreamEvents"
)

// K8SInfoClient is the client API for K8SInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type K8SInfoClient interface {
	ListPods(ctx context.Context, in *NamespaceRequest, opts ...grpc.CallOption) (*PodListResponse, error)
	GetNodeStats(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeStatsResponse, error)
	GetPodStats(ctx context.Context, in *PodRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PodStatsResponse], error)
	GetNodeRealTimeStats(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeStatsResponse], error)
	StreamEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error)
}

type k8SInfoClient struct {
	cc grpc.ClientConnInterface
}

func NewK8SInfoClient(cc grpc.ClientConnInterface) K8SInfoClient {
	return &k8SInfoClient{cc}
}

func (c *k8SInfoClient) ListPods(ctx context.Context, in *NamespaceRequest, opts ...grpc.CallOption) (*PodListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PodListResponse)
	err := c.cc.Invoke(ctx, K8SInfo_ListPods_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SInfoClient) GetNodeStats(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (*NodeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NodeStatsResponse)
	err := c.cc.Invoke(ctx, K8SInfo_GetNodeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *k8SInfoClient) GetPodStats(ctx context.Context, in *PodRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PodStatsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &K8SInfo_ServiceDesc.Streams[0], K8SInfo_GetPodStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PodRequest, PodStatsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SInfo_GetPodStatsClient = grpc.ServerStreamingClient[PodStatsResponse]

func (c *k8SInfoClient) GetNodeRealTimeStats(ctx context.Context, in *NodeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[NodeStatsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &K8SInfo_ServiceDesc.Streams[1], K8SInfo_GetNodeRealTimeStats_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeRequest, NodeStatsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SInfo_GetNodeRealTimeStatsClient = grpc.ServerStreamingClient[NodeStatsResponse]

func (c *k8SInfoClient) StreamEvents(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[EventResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &K8SInfo_ServiceDesc.Streams[2], K8SInfo_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[emptypb.Empty, EventResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SInfo_StreamEventsClient = grpc.ServerStreamingClient[EventResponse]

// K8SInfoServer is the server API for K8SInfo service.
// All implementations must embed UnimplementedK8SInfoServer
// for forward compatibility.
type K8SInfoServer interface {
	ListPods(context.Context, *NamespaceRequest) (*PodListResponse, error)
	GetNodeStats(context.Context, *NodeRequest) (*NodeStatsResponse, error)
	GetPodStats(*PodRequest, grpc.ServerStreamingServer[PodStatsResponse]) error
	GetNodeRealTimeStats(*NodeRequest, grpc.ServerStreamingServer[NodeStatsResponse]) error
	StreamEvents(*emptypb.Empty, grpc.ServerStreamingServer[EventResponse]) error
	mustEmbedUnimplementedK8SInfoServer()
}

// UnimplementedK8SInfoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedK8SInfoServer struct{}

func (UnimplementedK8SInfoServer) ListPods(context.Context, *NamespaceRequest) (*PodListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPods not implemented")
}
func (UnimplementedK8SInfoServer) GetNodeStats(context.Context, *NodeRequest) (*NodeStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNodeStats not implemented")
}
func (UnimplementedK8SInfoServer) GetPodStats(*PodRequest, grpc.ServerStreamingServer[PodStatsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetPodStats not implemented")
}
func (UnimplementedK8SInfoServer) GetNodeRealTimeStats(*NodeRequest, grpc.ServerStreamingServer[NodeStatsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetNodeRealTimeStats not implemented")
}
func (UnimplementedK8SInfoServer) StreamEvents(*emptypb.Empty, grpc.ServerStreamingServer[EventResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedK8SInfoServer) mustEmbedUnimplementedK8SInfoServer() {}
func (UnimplementedK8SInfoServer) testEmbeddedByValue()                 {}

// UnsafeK8SInfoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to K8SInfoServer will
// result in compilation errors.
type UnsafeK8SInfoServer interface {
	mustEmbedUnimplementedK8SInfoServer()
}

func RegisterK8SInfoServer(s grpc.ServiceRegistrar, srv K8SInfoServer) {
	// If the following call panics, it indicates UnimplementedK8SInfoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&K8SInfo_ServiceDesc, srv)
}

func _K8SInfo_ListPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SInfoServer).ListPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SInfo_ListPods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SInfoServer).ListPods(ctx, req.(*NamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SInfo_GetNodeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(K8SInfoServer).GetNodeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: K8SInfo_GetNodeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(K8SInfoServer).GetNodeStats(ctx, req.(*NodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _K8SInfo_GetPodStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PodRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(K8SInfoServer).GetPodStats(m, &grpc.GenericServerStream[PodRequest, PodStatsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SInfo_GetPodStatsServer = grpc.ServerStreamingServer[PodStatsResponse]

func _K8SInfo_GetNodeRealTimeStats_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NodeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(K8SInfoServer).GetNodeRealTimeStats(m, &grpc.GenericServerStream[NodeRequest, NodeStatsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SInfo_GetNodeRealTimeStatsServer = grpc.ServerStreamingServer[NodeStatsResponse]

func _K8SInfo_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(emptypb.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(K8SInfoServer).StreamEvents(m, &grpc.GenericServerStream[emptypb.Empty, EventResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type K8SInfo_StreamEventsServer = grpc.ServerStreamingServer[EventResponse]

// K8SInfo_ServiceDesc is the grpc.ServiceDesc for K8SInfo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var K8SInfo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "k8sinfo.K8sInfo",
	HandlerType: (*K8SInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListPods",
			Handler:    _K8SInfo_ListPods_Handler,
		},
		{
			MethodName: "GetNodeStats",
			Handler:    _K8SInfo_GetNodeStats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetPodStats",
			Handler:       _K8SInfo_GetPodStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetNodeRealTimeStats",
			Handler:       _K8SInfo_GetNodeRealTimeStats_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamEvents",
			Handler:       _K8SInfo_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/rampaz.proto",
}
