// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: rampaz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceRequest) Reset() {
	*x = NamespaceRequest{}
	mi := &file_rampaz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceRequest) ProtoMessage() {}

func (x *NamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceRequest.ProtoReflect.Descriptor instead.
func (*NamespaceRequest) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type PodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRequest) Reset() {
	*x = PodRequest{}
	mi := &file_rampaz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRequest) ProtoMessage() {}

func (x *PodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRequest.ProtoReflect.Descriptor instead.
func (*PodRequest) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{1}
}

func (x *PodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type PodStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Cpu           string                 `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatsResponse) Reset() {
	*x = PodStatsResponse{}
	mi := &file_rampaz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatsResponse) ProtoMessage() {}

func (x *PodStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatsResponse.ProtoReflect.Descriptor instead.
func (*PodStatsResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{2}
}

func (x *PodStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodStatsResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodStatsResponse) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *PodStatsResponse) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_rampaz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{3}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type PodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*Pod                 `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodListResponse) Reset() {
	*x = PodListResponse{}
	mi := &file_rampaz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodListResponse) ProtoMessage() {}

func (x *PodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodListResponse.ProtoReflect.Descriptor instead.
func (*PodListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{4}
}

func (x *PodListResponse) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_rampaz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{5}
}

func (x *NodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type NodeStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           string                 `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatsResponse) Reset() {
	*x = NodeStatsResponse{}
	mi := &file_rampaz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatsResponse) ProtoMessage() {}

func (x *NodeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatsResponse.ProtoReflect.Descriptor instead.
func (*NodeStatsResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{6}
}

func (x *NodeStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeStatsResponse) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *NodeStatsResponse) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type EventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	InvolvedObject string                 `protobuf:"bytes,4,opt,name=involvedObject,proto3" json:"involvedObject,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_rampaz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{7}
}

func (x *EventResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventResponse) GetInvolvedObject() string {
	if x != nil {
		return x.InvolvedObject
	}
	return ""
}

type Workload struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Name      string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Replica-related fields (not all apply to every workload)
	DesiredReplicas   int32 `protobuf:"varint,3,opt,name=desiredReplicas,proto3" json:"desiredReplicas,omitempty"`
	ReadyReplicas     int32 `protobuf:"varint,4,opt,name=readyReplicas,proto3" json:"readyReplicas,omitempty"`
	AvailableReplicas int32 `protobuf:"varint,5,opt,name=availableReplicas,proto3" json:"availableReplicas,omitempty"`
	UpdatedReplicas   int32 `protobuf:"varint,6,opt,name=updatedReplicas,proto3" json:"updatedReplicas,omitempty"`
	// Job-specific fields
	Active    int32 `protobuf:"varint,7,opt,name=active,proto3" json:"active,omitempty"`
	Succeeded int32 `protobuf:"varint,8,opt,name=succeeded,proto3" json:"succeeded,omitempty"`
	Failed    int32 `protobuf:"varint,9,opt,name=failed,proto3" json:"failed,omitempty"`
	// CronJob-specific fields
	Schedule         string `protobuf:"bytes,10,opt,name=schedule,proto3" json:"schedule,omitempty"`
	LastScheduleTime string `protobuf:"bytes,11,opt,name=lastScheduleTime,proto3" json:"lastScheduleTime,omitempty"`
	// Metadata
	Labels        map[string]string `protobuf:"bytes,12,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Conditions    []string          `protobuf:"bytes,13,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Owner         string            `protobuf:"bytes,14,opt,name=owner,proto3" json:"owner,omitempty"`
	Age           string            `protobuf:"bytes,15,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Workload) Reset() {
	*x = Workload{}
	mi := &file_rampaz_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Workload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workload) ProtoMessage() {}

func (x *Workload) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workload.ProtoReflect.Descriptor instead.
func (*Workload) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{8}
}

func (x *Workload) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Workload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Workload) GetDesiredReplicas() int32 {
	if x != nil {
		return x.DesiredReplicas
	}
	return 0
}

func (x *Workload) GetReadyReplicas() int32 {
	if x != nil {
		return x.ReadyReplicas
	}
	return 0
}

func (x *Workload) GetAvailableReplicas() int32 {
	if x != nil {
		return x.AvailableReplicas
	}
	return 0
}

func (x *Workload) GetUpdatedReplicas() int32 {
	if x != nil {
		return x.UpdatedReplicas
	}
	return 0
}

func (x *Workload) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *Workload) GetSucceeded() int32 {
	if x != nil {
		return x.Succeeded
	}
	return 0
}

func (x *Workload) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *Workload) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Workload) GetLastScheduleTime() string {
	if x != nil {
		return x.LastScheduleTime
	}
	return ""
}

func (x *Workload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Workload) GetConditions() []string {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *Workload) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Workload) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type WorkloadListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Workloads     []*Workload            `protobuf:"bytes,1,rep,name=workloads,proto3" json:"workloads,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadListResponse) Reset() {
	*x = WorkloadListResponse{}
	mi := &file_rampaz_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadListResponse) ProtoMessage() {}

func (x *WorkloadListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadListResponse.ProtoReflect.Descriptor instead.
func (*WorkloadListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{9}
}

func (x *WorkloadListResponse) GetWorkloads() []*Workload {
	if x != nil {
		return x.Workloads
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	ClusterIp     string                 `protobuf:"bytes,4,opt,name=cluster_ip,json=clusterIp,proto3" json:"cluster_ip,omitempty"`
	ExternalIps   []string               `protobuf:"bytes,5,rep,name=external_ips,json=externalIps,proto3" json:"external_ips,omitempty"`
	Ports         []string               `protobuf:"bytes,6,rep,name=ports,proto3" json:"ports,omitempty"`
	Age           string                 `protobuf:"bytes,7,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_rampaz_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ServiceInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ServiceInfo) GetClusterIp() string {
	if x != nil {
		return x.ClusterIp
	}
	return ""
}

func (x *ServiceInfo) GetExternalIps() []string {
	if x != nil {
		return x.ExternalIps
	}
	return nil
}

func (x *ServiceInfo) GetPorts() []string {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ServiceInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type ServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListResponse) Reset() {
	*x = ServiceListResponse{}
	mi := &file_rampaz_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListResponse) ProtoMessage() {}

func (x *ServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListResponse.ProtoReflect.Descriptor instead.
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{11}
}

func (x *ServiceListResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type NamespaceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Age           string                 `protobuf:"bytes,3,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceInfo) Reset() {
	*x = NamespaceInfo{}
	mi := &file_rampaz_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceInfo) ProtoMessage() {}

func (x *NamespaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceInfo.ProtoReflect.Descriptor instead.
func (*NamespaceInfo) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{12}
}

func (x *NamespaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NamespaceInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *NamespaceInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type NamespaceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespaces    []*NamespaceInfo       `protobuf:"bytes,1,rep,name=namespaces,proto3" json:"namespaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceListResponse) Reset() {
	*x = NamespaceListResponse{}
	mi := &file_rampaz_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceListResponse) ProtoMessage() {}

func (x *NamespaceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceListResponse.ProtoReflect.Descriptor instead.
func (*NamespaceListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{13}
}

func (x *NamespaceListResponse) GetNamespaces() []*NamespaceInfo {
	if x != nil {
		return x.Namespaces
	}
	return nil
}

type PVCInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Phase            string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	StorageClass     string                 `protobuf:"bytes,4,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	AccessModes      []string               `protobuf:"bytes,5,rep,name=access_modes,json=accessModes,proto3" json:"access_modes,omitempty"`
	RequestedStorage string                 `protobuf:"bytes,6,opt,name=requested_storage,json=requestedStorage,proto3" json:"requested_storage,omitempty"`
	VolumeName       string                 `protobuf:"bytes,7,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	Age              string                 `protobuf:"bytes,8,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PVCInfo) Reset() {
	*x = PVCInfo{}
	mi := &file_rampaz_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVCInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVCInfo) ProtoMessage() {}

func (x *PVCInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVCInfo.ProtoReflect.Descriptor instead.
func (*PVCInfo) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{14}
}

func (x *PVCInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PVCInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PVCInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PVCInfo) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *PVCInfo) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *PVCInfo) GetRequestedStorage() string {
	if x != nil {
		return x.RequestedStorage
	}
	return ""
}

func (x *PVCInfo) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *PVCInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type PVCListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvcs          []*PVCInfo             `protobuf:"bytes,1,rep,name=pvcs,proto3" json:"pvcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVCListResponse) Reset() {
	*x = PVCListResponse{}
	mi := &file_rampaz_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVCListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVCListResponse) ProtoMessage() {}

func (x *PVCListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVCListResponse.ProtoReflect.Descriptor instead.
func (*PVCListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{15}
}

func (x *PVCListResponse) GetPvcs() []*PVCInfo {
	if x != nil {
		return x.Pvcs
	}
	return nil
}

type PVInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase          string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	StorageClass   string                 `protobuf:"bytes,3,opt,name=storage_class,json=storageClass,proto3" json:"storage_class,omitempty"`
	Capacity       string                 `protobuf:"bytes,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	AccessModes    []string               `protobuf:"bytes,5,rep,name=access_modes,json=accessModes,proto3" json:"access_modes,omitempty"`
	VolumeMode     string                 `protobuf:"bytes,6,opt,name=volume_mode,json=volumeMode,proto3" json:"volume_mode,omitempty"`
	ClaimName      string                 `protobuf:"bytes,7,opt,name=claim_name,json=claimName,proto3" json:"claim_name,omitempty"`
	ClaimNamespace string                 `protobuf:"bytes,8,opt,name=claim_namespace,json=claimNamespace,proto3" json:"claim_namespace,omitempty"`
	Age            string                 `protobuf:"bytes,9,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PVInfo) Reset() {
	*x = PVInfo{}
	mi := &file_rampaz_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVInfo) ProtoMessage() {}

func (x *PVInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVInfo.ProtoReflect.Descriptor instead.
func (*PVInfo) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{16}
}

func (x *PVInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PVInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *PVInfo) GetStorageClass() string {
	if x != nil {
		return x.StorageClass
	}
	return ""
}

func (x *PVInfo) GetCapacity() string {
	if x != nil {
		return x.Capacity
	}
	return ""
}

func (x *PVInfo) GetAccessModes() []string {
	if x != nil {
		return x.AccessModes
	}
	return nil
}

func (x *PVInfo) GetVolumeMode() string {
	if x != nil {
		return x.VolumeMode
	}
	return ""
}

func (x *PVInfo) GetClaimName() string {
	if x != nil {
		return x.ClaimName
	}
	return ""
}

func (x *PVInfo) GetClaimNamespace() string {
	if x != nil {
		return x.ClaimNamespace
	}
	return ""
}

func (x *PVInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type PVListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvs           []*PVInfo              `protobuf:"bytes,1,rep,name=pvs,proto3" json:"pvs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PVListResponse) Reset() {
	*x = PVListResponse{}
	mi := &file_rampaz_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVListResponse) ProtoMessage() {}

func (x *PVListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVListResponse.ProtoReflect.Descriptor instead.
func (*PVListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{17}
}

func (x *PVListResponse) GetPvs() []*PVInfo {
	if x != nil {
		return x.Pvs
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	InternalIp    string                 `protobuf:"bytes,2,opt,name=internal_ip,json=internalIp,proto3" json:"internal_ip,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Age           string                 `protobuf:"bytes,4,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_rampaz_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{18}
}

func (x *NodeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeInfo) GetInternalIp() string {
	if x != nil {
		return x.InternalIp
	}
	return ""
}

func (x *NodeInfo) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *NodeInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type NodeListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeListResponse) Reset() {
	*x = NodeListResponse{}
	mi := &file_rampaz_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeListResponse) ProtoMessage() {}

func (x *NodeListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeListResponse.ProtoReflect.Descriptor instead.
func (*NodeListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{19}
}

func (x *NodeListResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type NetworkPolicyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PolicyTypes   []string               `protobuf:"bytes,3,rep,name=policy_types,json=policyTypes,proto3" json:"policy_types,omitempty"`
	PodSelector   string                 `protobuf:"bytes,4,opt,name=pod_selector,json=podSelector,proto3" json:"pod_selector,omitempty"`
	Age           string                 `protobuf:"bytes,5,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyInfo) Reset() {
	*x = NetworkPolicyInfo{}
	mi := &file_rampaz_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyInfo) ProtoMessage() {}

func (x *NetworkPolicyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyInfo.ProtoReflect.Descriptor instead.
func (*NetworkPolicyInfo) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{20}
}

func (x *NetworkPolicyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyInfo) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NetworkPolicyInfo) GetPolicyTypes() []string {
	if x != nil {
		return x.PolicyTypes
	}
	return nil
}

func (x *NetworkPolicyInfo) GetPodSelector() string {
	if x != nil {
		return x.PodSelector
	}
	return ""
}

func (x *NetworkPolicyInfo) GetAge() string {
	if x != nil {
		return x.Age
	}
	return ""
}

type NetworkPolicyListResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NetworkPolicies []*NetworkPolicyInfo   `protobuf:"bytes,1,rep,name=networkPolicies,proto3" json:"networkPolicies,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NetworkPolicyListResponse) Reset() {
	*x = NetworkPolicyListResponse{}
	mi := &file_rampaz_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyListResponse) ProtoMessage() {}

func (x *NetworkPolicyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyListResponse.ProtoReflect.Descriptor instead.
func (*NetworkPolicyListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{21}
}

func (x *NetworkPolicyListResponse) GetNetworkPolicies() []*NetworkPolicyInfo {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

type NamespaceSummaryResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Namespace              string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Pods                   int32                  `protobuf:"varint,2,opt,name=pods,proto3" json:"pods,omitempty"`
	Deployments            int32                  `protobuf:"varint,3,opt,name=deployments,proto3" json:"deployments,omitempty"`
	Replicasets            int32                  `protobuf:"varint,4,opt,name=replicasets,proto3" json:"replicasets,omitempty"`
	Statefulsets           int32                  `protobuf:"varint,5,opt,name=statefulsets,proto3" json:"statefulsets,omitempty"`
	Daemonsets             int32                  `protobuf:"varint,6,opt,name=daemonsets,proto3" json:"daemonsets,omitempty"`
	Jobs                   int32                  `protobuf:"varint,7,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Cronjobs               int32                  `protobuf:"varint,8,opt,name=cronjobs,proto3" json:"cronjobs,omitempty"`
	Services               int32                  `protobuf:"varint,9,opt,name=services,proto3" json:"services,omitempty"`
	PersistentVolumeClaims int32                  `protobuf:"varint,10,opt,name=persistent_volume_claims,json=persistentVolumeClaims,proto3" json:"persistent_volume_claims,omitempty"`
	NetworkPolicies        int32                  `protobuf:"varint,11,opt,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NamespaceSummaryResponse) Reset() {
	*x = NamespaceSummaryResponse{}
	mi := &file_rampaz_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceSummaryResponse) ProtoMessage() {}

func (x *NamespaceSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceSummaryResponse.ProtoReflect.Descriptor instead.
func (*NamespaceSummaryResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{22}
}

func (x *NamespaceSummaryResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *NamespaceSummaryResponse) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetDeployments() int32 {
	if x != nil {
		return x.Deployments
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetReplicasets() int32 {
	if x != nil {
		return x.Replicasets
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetStatefulsets() int32 {
	if x != nil {
		return x.Statefulsets
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetDaemonsets() int32 {
	if x != nil {
		return x.Daemonsets
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetJobs() int32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetCronjobs() int32 {
	if x != nil {
		return x.Cronjobs
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetServices() int32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetPersistentVolumeClaims() int32 {
	if x != nil {
		return x.PersistentVolumeClaims
	}
	return 0
}

func (x *NamespaceSummaryResponse) GetNetworkPolicies() int32 {
	if x != nil {
		return x.NetworkPolicies
	}
	return 0
}

type ClusterOverviewResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Nodes                  int32                  `protobuf:"varint,1,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Namespaces             int32                  `protobuf:"varint,2,opt,name=namespaces,proto3" json:"namespaces,omitempty"`
	Pods                   int32                  `protobuf:"varint,3,opt,name=pods,proto3" json:"pods,omitempty"`
	Deployments            int32                  `protobuf:"varint,4,opt,name=deployments,proto3" json:"deployments,omitempty"`
	Replicasets            int32                  `protobuf:"varint,5,opt,name=replicasets,proto3" json:"replicasets,omitempty"`
	Statefulsets           int32                  `protobuf:"varint,6,opt,name=statefulsets,proto3" json:"statefulsets,omitempty"`
	Daemonsets             int32                  `protobuf:"varint,7,opt,name=daemonsets,proto3" json:"daemonsets,omitempty"`
	Jobs                   int32                  `protobuf:"varint,8,opt,name=jobs,proto3" json:"jobs,omitempty"`
	Cronjobs               int32                  `protobuf:"varint,9,opt,name=cronjobs,proto3" json:"cronjobs,omitempty"`
	Services               int32                  `protobuf:"varint,10,opt,name=services,proto3" json:"services,omitempty"`
	PersistentVolumeClaims int32                  `protobuf:"varint,11,opt,name=persistent_volume_claims,json=persistentVolumeClaims,proto3" json:"persistent_volume_claims,omitempty"`
	Ingresses              int32                  `protobuf:"varint,12,opt,name=ingresses,proto3" json:"ingresses,omitempty"`
	Secrets                int32                  `protobuf:"varint,13,opt,name=secrets,proto3" json:"secrets,omitempty"`
	Configmaps             int32                  `protobuf:"varint,14,opt,name=configmaps,proto3" json:"configmaps,omitempty"`
	Serviceaccounts        int32                  `protobuf:"varint,15,opt,name=serviceaccounts,proto3" json:"serviceaccounts,omitempty"`
	NetworkPolicies        int32                  `protobuf:"varint,16,opt,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ClusterOverviewResponse) Reset() {
	*x = ClusterOverviewResponse{}
	mi := &file_rampaz_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterOverviewResponse) ProtoMessage() {}

func (x *ClusterOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterOverviewResponse.ProtoReflect.Descriptor instead.
func (*ClusterOverviewResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{23}
}

func (x *ClusterOverviewResponse) GetNodes() int32 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *ClusterOverviewResponse) GetNamespaces() int32 {
	if x != nil {
		return x.Namespaces
	}
	return 0
}

func (x *ClusterOverviewResponse) GetPods() int32 {
	if x != nil {
		return x.Pods
	}
	return 0
}

func (x *ClusterOverviewResponse) GetDeployments() int32 {
	if x != nil {
		return x.Deployments
	}
	return 0
}

func (x *ClusterOverviewResponse) GetReplicasets() int32 {
	if x != nil {
		return x.Replicasets
	}
	return 0
}

func (x *ClusterOverviewResponse) GetStatefulsets() int32 {
	if x != nil {
		return x.Statefulsets
	}
	return 0
}

func (x *ClusterOverviewResponse) GetDaemonsets() int32 {
	if x != nil {
		return x.Daemonsets
	}
	return 0
}

func (x *ClusterOverviewResponse) GetJobs() int32 {
	if x != nil {
		return x.Jobs
	}
	return 0
}

func (x *ClusterOverviewResponse) GetCronjobs() int32 {
	if x != nil {
		return x.Cronjobs
	}
	return 0
}

func (x *ClusterOverviewResponse) GetServices() int32 {
	if x != nil {
		return x.Services
	}
	return 0
}

func (x *ClusterOverviewResponse) GetPersistentVolumeClaims() int32 {
	if x != nil {
		return x.PersistentVolumeClaims
	}
	return 0
}

func (x *ClusterOverviewResponse) GetIngresses() int32 {
	if x != nil {
		return x.Ingresses
	}
	return 0
}

func (x *ClusterOverviewResponse) GetSecrets() int32 {
	if x != nil {
		return x.Secrets
	}
	return 0
}

func (x *ClusterOverviewResponse) GetConfigmaps() int32 {
	if x != nil {
		return x.Configmaps
	}
	return 0
}

func (x *ClusterOverviewResponse) GetServiceaccounts() int32 {
	if x != nil {
		return x.Serviceaccounts
	}
	return 0
}

func (x *ClusterOverviewResponse) GetNetworkPolicies() int32 {
	if x != nil {
		return x.NetworkPolicies
	}
	return 0
}

var File_rampaz_proto protoreflect.FileDescriptor

const file_rampaz_proto_rawDesc = "" +
	"\n" +
	"\frampaz.proto\x12\ak8sinfo\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x10NamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"*\n" +
	"\n" +
	"PodRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"n\n" +
	"\x10PodStatsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\tR\x06memory\"k\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bnodeName\x18\x04 \x01(\tR\bnodeName\"3\n" +
	"\x0fPodListResponse\x12 \n" +
	"\x04pods\x18\x01 \x03(\v2\f.k8sinfo.PodR\x04pods\")\n" +
	"\vNodeRequest\x12\x1a\n" +
	"\bnodeName\x18\x01 \x01(\tR\bnodeName\"Q\n" +
	"\x11NodeStatsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\tR\x06memory\"}\n" +
	"\rEventResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0einvolvedObject\x18\x04 \x01(\tR\x0einvolvedObject\"\xb4\x04\n" +
	"\bWorkload\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12(\n" +
	"\x0fdesiredReplicas\x18\x03 \x01(\x05R\x0fdesiredReplicas\x12$\n" +
	"\rreadyReplicas\x18\x04 \x01(\x05R\rreadyReplicas\x12,\n" +
	"\x11availableReplicas\x18\x05 \x01(\x05R\x11availableReplicas\x12(\n" +
	"\x0fupdatedReplicas\x18\x06 \x01(\x05R\x0fupdatedReplicas\x12\x16\n" +
	"\x06active\x18\a \x01(\x05R\x06active\x12\x1c\n" +
	"\tsucceeded\x18\b \x01(\x05R\tsucceeded\x12\x16\n" +
	"\x06failed\x18\t \x01(\x05R\x06failed\x12\x1a\n" +
	"\bschedule\x18\n" +
	" \x01(\tR\bschedule\x12*\n" +
	"\x10lastScheduleTime\x18\v \x01(\tR\x10lastScheduleTime\x125\n" +
	"\x06labels\x18\f \x03(\v2\x1d.k8sinfo.Workload.LabelsEntryR\x06labels\x12\x1e\n" +
	"\n" +
	"conditions\x18\r \x03(\tR\n" +
	"conditions\x12\x14\n" +
	"\x05owner\x18\x0e \x01(\tR\x05owner\x12\x10\n" +
	"\x03age\x18\x0f \x01(\tR\x03age\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"G\n" +
	"\x14WorkloadListResponse\x12/\n" +
	"\tworkloads\x18\x01 \x03(\v2\x11.k8sinfo.WorkloadR\tworkloads\"\xbd\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1d\n" +
	"\n" +
	"cluster_ip\x18\x04 \x01(\tR\tclusterIp\x12!\n" +
	"\fexternal_ips\x18\x05 \x03(\tR\vexternalIps\x12\x14\n" +
	"\x05ports\x18\x06 \x03(\tR\x05ports\x12\x10\n" +
	"\x03age\x18\a \x01(\tR\x03age\"G\n" +
	"\x13ServiceListResponse\x120\n" +
	"\bservices\x18\x01 \x03(\v2\x14.k8sinfo.ServiceInfoR\bservices\"K\n" +
	"\rNamespaceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x10\n" +
	"\x03age\x18\x03 \x01(\tR\x03age\"O\n" +
	"\x15NamespaceListResponse\x126\n" +
	"\n" +
	"namespaces\x18\x01 \x03(\v2\x16.k8sinfo.NamespaceInfoR\n" +
	"namespaces\"\xf9\x01\n" +
	"\aPVCInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12#\n" +
	"\rstorage_class\x18\x04 \x01(\tR\fstorageClass\x12!\n" +
	"\faccess_modes\x18\x05 \x03(\tR\vaccessModes\x12+\n" +
	"\x11requested_storage\x18\x06 \x01(\tR\x10requestedStorage\x12\x1f\n" +
	"\vvolume_name\x18\a \x01(\tR\n" +
	"volumeName\x12\x10\n" +
	"\x03age\x18\b \x01(\tR\x03age\"7\n" +
	"\x0fPVCListResponse\x12$\n" +
	"\x04pvcs\x18\x01 \x03(\v2\x10.k8sinfo.PVCInfoR\x04pvcs\"\x91\x02\n" +
	"\x06PVInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12#\n" +
	"\rstorage_class\x18\x03 \x01(\tR\fstorageClass\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\tR\bcapacity\x12!\n" +
	"\faccess_modes\x18\x05 \x03(\tR\vaccessModes\x12\x1f\n" +
	"\vvolume_mode\x18\x06 \x01(\tR\n" +
	"volumeMode\x12\x1d\n" +
	"\n" +
	"claim_name\x18\a \x01(\tR\tclaimName\x12'\n" +
	"\x0fclaim_namespace\x18\b \x01(\tR\x0eclaimNamespace\x12\x10\n" +
	"\x03age\x18\t \x01(\tR\x03age\"3\n" +
	"\x0ePVListResponse\x12!\n" +
	"\x03pvs\x18\x01 \x03(\v2\x0f.k8sinfo.PVInfoR\x03pvs\"g\n" +
	"\bNodeInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1f\n" +
	"\vinternal_ip\x18\x02 \x01(\tR\n" +
	"internalIp\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x10\n" +
	"\x03age\x18\x04 \x01(\tR\x03age\";\n" +
	"\x10NodeListResponse\x12'\n" +
	"\x05nodes\x18\x01 \x03(\v2\x11.k8sinfo.NodeInfoR\x05nodes\"\x9d\x01\n" +
	"\x11NetworkPolicyInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12!\n" +
	"\fpolicy_types\x18\x03 \x03(\tR\vpolicyTypes\x12!\n" +
	"\fpod_selector\x18\x04 \x01(\tR\vpodSelector\x12\x10\n" +
	"\x03age\x18\x05 \x01(\tR\x03age\"a\n" +
	"\x19NetworkPolicyListResponse\x12D\n" +
	"\x0fnetworkPolicies\x18\x01 \x03(\v2\x1a.k8sinfo.NetworkPolicyInfoR\x0fnetworkPolicies\"\x85\x03\n" +
	"\x18NamespaceSummaryResponse\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04pods\x18\x02 \x01(\x05R\x04pods\x12 \n" +
	"\vdeployments\x18\x03 \x01(\x05R\vdeployments\x12 \n" +
	"\vreplicasets\x18\x04 \x01(\x05R\vreplicasets\x12\"\n" +
	"\fstatefulsets\x18\x05 \x01(\x05R\fstatefulsets\x12\x1e\n" +
	"\n" +
	"daemonsets\x18\x06 \x01(\x05R\n" +
	"daemonsets\x12\x12\n" +
	"\x04jobs\x18\a \x01(\x05R\x04jobs\x12\x1a\n" +
	"\bcronjobs\x18\b \x01(\x05R\bcronjobs\x12\x1a\n" +
	"\bservices\x18\t \x01(\x05R\bservices\x128\n" +
	"\x18persistent_volume_claims\x18\n" +
	" \x01(\x05R\x16persistentVolumeClaims\x12)\n" +
	"\x10network_policies\x18\v \x01(\x05R\x0fnetworkPolicies\"\x9e\x04\n" +
	"\x17ClusterOverviewResponse\x12\x14\n" +
	"\x05nodes\x18\x01 \x01(\x05R\x05nodes\x12\x1e\n" +
	"\n" +
	"namespaces\x18\x02 \x01(\x05R\n" +
	"namespaces\x12\x12\n" +
	"\x04pods\x18\x03 \x01(\x05R\x04pods\x12 \n" +
	"\vdeployments\x18\x04 \x01(\x05R\vdeployments\x12 \n" +
	"\vreplicasets\x18\x05 \x01(\x05R\vreplicasets\x12\"\n" +
	"\fstatefulsets\x18\x06 \x01(\x05R\fstatefulsets\x12\x1e\n" +
	"\n" +
	"daemonsets\x18\a \x01(\x05R\n" +
	"daemonsets\x12\x12\n" +
	"\x04jobs\x18\b \x01(\x05R\x04jobs\x12\x1a\n" +
	"\bcronjobs\x18\t \x01(\x05R\bcronjobs\x12\x1a\n" +
	"\bservices\x18\n" +
	" \x01(\x05R\bservices\x128\n" +
	"\x18persistent_volume_claims\x18\v \x01(\x05R\x16persistentVolumeClaims\x12\x1c\n" +
	"\tingresses\x18\f \x01(\x05R\tingresses\x12\x18\n" +
	"\asecrets\x18\r \x01(\x05R\asecrets\x12\x1e\n" +
	"\n" +
	"configmaps\x18\x0e \x01(\x05R\n" +
	"configmaps\x12(\n" +
	"\x0fserviceaccounts\x18\x0f \x01(\x05R\x0fserviceaccounts\x12)\n" +
	"\x10network_policies\x18\x10 \x01(\x05R\x0fnetworkPolicies2\xea\n" +
	"\n" +
	"\aK8sInfo\x12?\n" +
	"\bListPods\x12\x19.k8sinfo.NamespaceRequest\x1a\x18.k8sinfo.PodListResponse\x12@\n" +
	"\fGetNodeStats\x12\x14.k8sinfo.NodeRequest\x1a\x1a.k8sinfo.NodeStatsResponse\x12?\n" +
	"\vGetPodStats\x12\x13.k8sinfo.PodRequest\x1a\x19.k8sinfo.PodStatsResponse0\x01\x12J\n" +
	"\x14GetNodeRealTimeStats\x12\x14.k8sinfo.NodeRequest\x1a\x1a.k8sinfo.NodeStatsResponse0\x01\x12@\n" +
	"\fStreamEvents\x12\x16.google.protobuf.Empty\x1a\x16.k8sinfo.EventResponse0\x01\x12K\n" +
	"\x0fListDeployments\x12\x19.k8sinfo.NamespaceRequest\x1a\x1d.k8sinfo.WorkloadListResponse\x12K\n" +
	"\x0fListReplicaSets\x12\x19.k8sinfo.NamespaceRequest\x1a\x1d.k8sinfo.WorkloadListResponse\x12L\n" +
	"\x10ListStatefulSets\x12\x19.k8sinfo.NamespaceRequest\x1a\x1d.k8sinfo.WorkloadListResponse\x12J\n" +
	"\x0eListDaemonSets\x12\x19.k8sinfo.NamespaceRequest\x1a\x1d.k8sinfo.WorkloadListResponse\x12D\n" +
	"\bListJobs\x12\x19.k8sinfo.NamespaceRequest\x1a\x1d.k8sinfo.WorkloadListResponse\x12H\n" +
	"\fListCronJobs\x12\x19.k8sinfo.NamespaceRequest\x1a\x1d.k8sinfo.WorkloadListResponse\x12G\n" +
	"\fListServices\x12\x19.k8sinfo.NamespaceRequest\x1a\x1c.k8sinfo.ServiceListResponse\x12H\n" +
	"\x0eListNamespaces\x12\x16.google.protobuf.Empty\x1a\x1e.k8sinfo.NamespaceListResponse\x12?\n" +
	"\bListPVCs\x12\x19.k8sinfo.NamespaceRequest\x1a\x18.k8sinfo.PVCListResponse\x12:\n" +
	"\aListPVs\x12\x16.google.protobuf.Empty\x1a\x17.k8sinfo.PVListResponse\x12>\n" +
	"\tListNodes\x12\x16.google.protobuf.Empty\x1a\x19.k8sinfo.NodeListResponse\x12T\n" +
	"\x13ListNetworkPolicies\x12\x19.k8sinfo.NamespaceRequest\x1a\".k8sinfo.NetworkPolicyListResponse\x12S\n" +
	"\x13GetNamespaceSummary\x12\x19.k8sinfo.NamespaceRequest\x1a!.k8sinfo.NamespaceSummaryResponse\x12N\n" +
	"\x12GetClusterOverview\x12\x16.google.protobuf.Empty\x1a .k8sinfo.ClusterOverviewResponseB&Z$github.com/Mujib-Ahasan/Rampaz/protob\x06proto3"

var (
	file_rampaz_proto_rawDescOnce sync.Once
	file_rampaz_proto_rawDescData []byte
)

func file_rampaz_proto_rawDescGZIP() []byte {
	file_rampaz_proto_rawDescOnce.Do(func() {
		file_rampaz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rampaz_proto_rawDesc), len(file_rampaz_proto_rawDesc)))
	})
	return file_rampaz_proto_rawDescData
}

var file_rampaz_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_rampaz_proto_goTypes = []any{
	(*NamespaceRequest)(nil),          // 0: k8sinfo.NamespaceRequest
	(*PodRequest)(nil),                // 1: k8sinfo.PodRequest
	(*PodStatsResponse)(nil),          // 2: k8sinfo.PodStatsResponse
	(*Pod)(nil),                       // 3: k8sinfo.Pod
	(*PodListResponse)(nil),           // 4: k8sinfo.PodListResponse
	(*NodeRequest)(nil),               // 5: k8sinfo.NodeRequest
	(*NodeStatsResponse)(nil),         // 6: k8sinfo.NodeStatsResponse
	(*EventResponse)(nil),             // 7: k8sinfo.EventResponse
	(*Workload)(nil),                  // 8: k8sinfo.Workload
	(*WorkloadListResponse)(nil),      // 9: k8sinfo.WorkloadListResponse
	(*ServiceInfo)(nil),               // 10: k8sinfo.ServiceInfo
	(*ServiceListResponse)(nil),       // 11: k8sinfo.ServiceListResponse
	(*NamespaceInfo)(nil),             // 12: k8sinfo.NamespaceInfo
	(*NamespaceListResponse)(nil),     // 13: k8sinfo.NamespaceListResponse
	(*PVCInfo)(nil),                   // 14: k8sinfo.PVCInfo
	(*PVCListResponse)(nil),           // 15: k8sinfo.PVCListResponse
	(*PVInfo)(nil),                    // 16: k8sinfo.PVInfo
	(*PVListResponse)(nil),            // 17: k8sinfo.PVListResponse
	(*NodeInfo)(nil),                  // 18: k8sinfo.NodeInfo
	(*NodeListResponse)(nil),          // 19: k8sinfo.NodeListResponse
	(*NetworkPolicyInfo)(nil),         // 20: k8sinfo.NetworkPolicyInfo
	(*NetworkPolicyListResponse)(nil), // 21: k8sinfo.NetworkPolicyListResponse
	(*NamespaceSummaryResponse)(nil),  // 22: k8sinfo.NamespaceSummaryResponse
	(*ClusterOverviewResponse)(nil),   // 23: k8sinfo.ClusterOverviewResponse
	nil,                               // 24: k8sinfo.Workload.LabelsEntry
	(*emptypb.Empty)(nil),             // 25: google.protobuf.Empty
}
var file_rampaz_proto_depIdxs = []int32{
	3,  // 0: k8sinfo.PodListResponse.pods:type_name -> k8sinfo.Pod
	24, // 1: k8sinfo.Workload.labels:type_name -> k8sinfo.Workload.LabelsEntry
	8,  // 2: k8sinfo.WorkloadListResponse.workloads:type_name -> k8sinfo.Workload
	10, // 3: k8sinfo.ServiceListResponse.services:type_name -> k8sinfo.ServiceInfo
	12, // 4: k8sinfo.NamespaceListResponse.namespaces:type_name -> k8sinfo.NamespaceInfo
	14, // 5: k8sinfo.PVCListResponse.pvcs:type_name -> k8sinfo.PVCInfo
	16, // 6: k8sinfo.PVListResponse.pvs:type_name -> k8sinfo.PVInfo
	18, // 7: k8sinfo.NodeListResponse.nodes:type_name -> k8sinfo.NodeInfo
	20, // 8: k8sinfo.NetworkPolicyListResponse.networkPolicies:type_name -> k8sinfo.NetworkPolicyInfo
	0,  // 9: k8sinfo.K8sInfo.ListPods:input_type -> k8sinfo.NamespaceRequest
	5,  // 10: k8sinfo.K8sInfo.GetNodeStats:input_type -> k8sinfo.NodeRequest
	1,  // 11: k8sinfo.K8sInfo.GetPodStats:input_type -> k8sinfo.PodRequest
	5,  // 12: k8sinfo.K8sInfo.GetNodeRealTimeStats:input_type -> k8sinfo.NodeRequest
	25, // 13: k8sinfo.K8sInfo.StreamEvents:input_type -> google.protobuf.Empty
	0,  // 14: k8sinfo.K8sInfo.ListDeployments:input_type -> k8sinfo.NamespaceRequest
	0,  // 15: k8sinfo.K8sInfo.ListReplicaSets:input_type -> k8sinfo.NamespaceRequest
	0,  // 16: k8sinfo.K8sInfo.ListStatefulSets:input_type -> k8sinfo.NamespaceRequest
	0,  // 17: k8sinfo.K8sInfo.ListDaemonSets:input_type -> k8sinfo.NamespaceRequest
	0,  // 18: k8sinfo.K8sInfo.ListJobs:input_type -> k8sinfo.NamespaceRequest
	0,  // 19: k8sinfo.K8sInfo.ListCronJobs:input_type -> k8sinfo.NamespaceRequest
	0,  // 20: k8sinfo.K8sInfo.ListServices:input_type -> k8sinfo.NamespaceRequest
	25, // 21: k8sinfo.K8sInfo.ListNamespaces:input_type -> google.protobuf.Empty
	0,  // 22: k8sinfo.K8sInfo.ListPVCs:input_type -> k8sinfo.NamespaceRequest
	25, // 23: k8sinfo.K8sInfo.ListPVs:input_type -> google.protobuf.Empty
	25, // 24: k8sinfo.K8sInfo.ListNodes:input_type -> google.protobuf.Empty
	0,  // 25: k8sinfo.K8sInfo.ListNetworkPolicies:input_type -> k8sinfo.NamespaceRequest
	0,  // 26: k8sinfo.K8sInfo.GetNamespaceSummary:input_type -> k8sinfo.NamespaceRequest
	25, // 27: k8sinfo.K8sInfo.GetClusterOverview:input_type -> google.protobuf.Empty
	4,  // 28: k8sinfo.K8sInfo.ListPods:output_type -> k8sinfo.PodListResponse
	6,  // 29: k8sinfo.K8sInfo.GetNodeStats:output_type -> k8sinfo.NodeStatsResponse
	2,  // 30: k8sinfo.K8sInfo.GetPodStats:output_type -> k8sinfo.PodStatsResponse
	6,  // 31: k8sinfo.K8sInfo.GetNodeRealTimeStats:output_type -> k8sinfo.NodeStatsResponse
	7,  // 32: k8sinfo.K8sInfo.StreamEvents:output_type -> k8sinfo.EventResponse
	9,  // 33: k8sinfo.K8sInfo.ListDeployments:output_type -> k8sinfo.WorkloadListResponse
	9,  // 34: k8sinfo.K8sInfo.ListReplicaSets:output_type -> k8sinfo.WorkloadListResponse
	9,  // 35: k8sinfo.K8sInfo.ListStatefulSets:output_type -> k8sinfo.WorkloadListResponse
	9,  // 36: k8sinfo.K8sInfo.ListDaemonSets:output_type -> k8sinfo.WorkloadListResponse
	9,  // 37: k8sinfo.K8sInfo.ListJobs:output_type -> k8sinfo.WorkloadListResponse
	9,  // 38: k8sinfo.K8sInfo.ListCronJobs:output_type -> k8sinfo.WorkloadListResponse
	11, // 39: k8sinfo.K8sInfo.ListServices:output_type -> k8sinfo.ServiceListResponse
	13, // 40: k8sinfo.K8sInfo.ListNamespaces:output_type -> k8sinfo.NamespaceListResponse
	15, // 41: k8sinfo.K8sInfo.ListPVCs:output_type -> k8sinfo.PVCListResponse
	17, // 42: k8sinfo.K8sInfo.ListPVs:output_type -> k8sinfo.PVListResponse
	19, // 43: k8sinfo.K8sInfo.ListNodes:output_type -> k8sinfo.NodeListResponse
	21, // 44: k8sinfo.K8sInfo.ListNetworkPolicies:output_type -> k8sinfo.NetworkPolicyListResponse
	22, // 45: k8sinfo.K8sInfo.GetNamespaceSummary:output_type -> k8sinfo.NamespaceSummaryResponse
	23, // 46: k8sinfo.K8sInfo.GetClusterOverview:output_type -> k8sinfo.ClusterOverviewResponse
	28, // [28:47] is the sub-list for method output_type
	9,  // [9:28] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_rampaz_proto_init() }
func file_rampaz_proto_init() {
	if File_rampaz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rampaz_proto_rawDesc), len(file_rampaz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rampaz_proto_goTypes,
		DependencyIndexes: file_rampaz_proto_depIdxs,
		MessageInfos:      file_rampaz_proto_msgTypes,
	}.Build()
	File_rampaz_proto = out.File
	file_rampaz_proto_goTypes = nil
	file_rampaz_proto_depIdxs = nil
}
