// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: rampaz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NamespaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NamespaceRequest) Reset() {
	*x = NamespaceRequest{}
	mi := &file_rampaz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NamespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NamespaceRequest) ProtoMessage() {}

func (x *NamespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NamespaceRequest.ProtoReflect.Descriptor instead.
func (*NamespaceRequest) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{0}
}

func (x *NamespaceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type PodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodRequest) Reset() {
	*x = PodRequest{}
	mi := &file_rampaz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodRequest) ProtoMessage() {}

func (x *PodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodRequest.ProtoReflect.Descriptor instead.
func (*PodRequest) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{1}
}

func (x *PodRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type PodStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Cpu           string                 `protobuf:"bytes,3,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,4,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodStatsResponse) Reset() {
	*x = PodStatsResponse{}
	mi := &file_rampaz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodStatsResponse) ProtoMessage() {}

func (x *PodStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodStatsResponse.ProtoReflect.Descriptor instead.
func (*PodStatsResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{2}
}

func (x *PodStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PodStatsResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodStatsResponse) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *PodStatsResponse) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type Pod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pod) Reset() {
	*x = Pod{}
	mi := &file_rampaz_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pod) ProtoMessage() {}

func (x *Pod) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pod.ProtoReflect.Descriptor instead.
func (*Pod) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{3}
}

func (x *Pod) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pod) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pod) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Pod) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type PodListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pods          []*Pod                 `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodListResponse) Reset() {
	*x = PodListResponse{}
	mi := &file_rampaz_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodListResponse) ProtoMessage() {}

func (x *PodListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodListResponse.ProtoReflect.Descriptor instead.
func (*PodListResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{4}
}

func (x *PodListResponse) GetPods() []*Pod {
	if x != nil {
		return x.Pods
	}
	return nil
}

type NodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeRequest) Reset() {
	*x = NodeRequest{}
	mi := &file_rampaz_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRequest) ProtoMessage() {}

func (x *NodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRequest.ProtoReflect.Descriptor instead.
func (*NodeRequest) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{5}
}

func (x *NodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type NodeStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Cpu           string                 `protobuf:"bytes,2,opt,name=cpu,proto3" json:"cpu,omitempty"`
	Memory        string                 `protobuf:"bytes,3,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeStatsResponse) Reset() {
	*x = NodeStatsResponse{}
	mi := &file_rampaz_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatsResponse) ProtoMessage() {}

func (x *NodeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatsResponse.ProtoReflect.Descriptor instead.
func (*NodeStatsResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{6}
}

func (x *NodeStatsResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NodeStatsResponse) GetCpu() string {
	if x != nil {
		return x.Cpu
	}
	return ""
}

func (x *NodeStatsResponse) GetMemory() string {
	if x != nil {
		return x.Memory
	}
	return ""
}

type EventResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	InvolvedObject string                 `protobuf:"bytes,4,opt,name=involvedObject,proto3" json:"involvedObject,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventResponse) Reset() {
	*x = EventResponse{}
	mi := &file_rampaz_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventResponse) ProtoMessage() {}

func (x *EventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rampaz_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventResponse.ProtoReflect.Descriptor instead.
func (*EventResponse) Descriptor() ([]byte, []int) {
	return file_rampaz_proto_rawDescGZIP(), []int{7}
}

func (x *EventResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *EventResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EventResponse) GetInvolvedObject() string {
	if x != nil {
		return x.InvolvedObject
	}
	return ""
}

var File_rampaz_proto protoreflect.FileDescriptor

const file_rampaz_proto_rawDesc = "" +
	"\n" +
	"\frampaz.proto\x12\ak8sinfo\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x10NamespaceRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"*\n" +
	"\n" +
	"PodRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"n\n" +
	"\x10PodStatsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x10\n" +
	"\x03cpu\x18\x03 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x04 \x01(\tR\x06memory\"k\n" +
	"\x03Pod\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1a\n" +
	"\bnodeName\x18\x04 \x01(\tR\bnodeName\"3\n" +
	"\x0fPodListResponse\x12 \n" +
	"\x04pods\x18\x01 \x03(\v2\f.k8sinfo.PodR\x04pods\")\n" +
	"\vNodeRequest\x12\x1a\n" +
	"\bnodeName\x18\x01 \x01(\tR\bnodeName\"Q\n" +
	"\x11NodeStatsResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03cpu\x18\x02 \x01(\tR\x03cpu\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\tR\x06memory\"}\n" +
	"\rEventResponse\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12&\n" +
	"\x0einvolvedObject\x18\x04 \x01(\tR\x0einvolvedObject2\xd9\x02\n" +
	"\aK8sInfo\x12?\n" +
	"\bListPods\x12\x19.k8sinfo.NamespaceRequest\x1a\x18.k8sinfo.PodListResponse\x12@\n" +
	"\fGetNodeStats\x12\x14.k8sinfo.NodeRequest\x1a\x1a.k8sinfo.NodeStatsResponse\x12?\n" +
	"\vGetPodStats\x12\x13.k8sinfo.PodRequest\x1a\x19.k8sinfo.PodStatsResponse0\x01\x12H\n" +
	"\x14GetNodeRealTimeStats\x12\x14.k8sinfo.NodeRequest\x1a\x1a.k8sinfo.NodeStatsResponse\x12@\n" +
	"\fStreamEvents\x12\x16.google.protobuf.Empty\x1a\x16.k8sinfo.EventResponse0\x01B&Z$github.com/Mujib-Ahasan/Rampaz/protob\x06proto3"

var (
	file_rampaz_proto_rawDescOnce sync.Once
	file_rampaz_proto_rawDescData []byte
)

func file_rampaz_proto_rawDescGZIP() []byte {
	file_rampaz_proto_rawDescOnce.Do(func() {
		file_rampaz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rampaz_proto_rawDesc), len(file_rampaz_proto_rawDesc)))
	})
	return file_rampaz_proto_rawDescData
}

var file_rampaz_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rampaz_proto_goTypes = []any{
	(*NamespaceRequest)(nil),  // 0: k8sinfo.NamespaceRequest
	(*PodRequest)(nil),        // 1: k8sinfo.PodRequest
	(*PodStatsResponse)(nil),  // 2: k8sinfo.PodStatsResponse
	(*Pod)(nil),               // 3: k8sinfo.Pod
	(*PodListResponse)(nil),   // 4: k8sinfo.PodListResponse
	(*NodeRequest)(nil),       // 5: k8sinfo.NodeRequest
	(*NodeStatsResponse)(nil), // 6: k8sinfo.NodeStatsResponse
	(*EventResponse)(nil),     // 7: k8sinfo.EventResponse
	(*emptypb.Empty)(nil),     // 8: google.protobuf.Empty
}
var file_rampaz_proto_depIdxs = []int32{
	3, // 0: k8sinfo.PodListResponse.pods:type_name -> k8sinfo.Pod
	0, // 1: k8sinfo.K8sInfo.ListPods:input_type -> k8sinfo.NamespaceRequest
	5, // 2: k8sinfo.K8sInfo.GetNodeStats:input_type -> k8sinfo.NodeRequest
	1, // 3: k8sinfo.K8sInfo.GetPodStats:input_type -> k8sinfo.PodRequest
	5, // 4: k8sinfo.K8sInfo.GetNodeRealTimeStats:input_type -> k8sinfo.NodeRequest
	8, // 5: k8sinfo.K8sInfo.StreamEvents:input_type -> google.protobuf.Empty
	4, // 6: k8sinfo.K8sInfo.ListPods:output_type -> k8sinfo.PodListResponse
	6, // 7: k8sinfo.K8sInfo.GetNodeStats:output_type -> k8sinfo.NodeStatsResponse
	2, // 8: k8sinfo.K8sInfo.GetPodStats:output_type -> k8sinfo.PodStatsResponse
	6, // 9: k8sinfo.K8sInfo.GetNodeRealTimeStats:output_type -> k8sinfo.NodeStatsResponse
	7, // 10: k8sinfo.K8sInfo.StreamEvents:output_type -> k8sinfo.EventResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rampaz_proto_init() }
func file_rampaz_proto_init() {
	if File_rampaz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rampaz_proto_rawDesc), len(file_rampaz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rampaz_proto_goTypes,
		DependencyIndexes: file_rampaz_proto_depIdxs,
		MessageInfos:      file_rampaz_proto_msgTypes,
	}.Build()
	File_rampaz_proto = out.File
	file_rampaz_proto_goTypes = nil
	file_rampaz_proto_depIdxs = nil
}
