apiVersion: apps/v1
kind: Deployment
metadata:
  name: rampaz-server
  namespace: rampaz
  labels:
    app: rampaz-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rampaz-server
  template:
    metadata:
      labels:
        app: rampaz-server
    spec:
      serviceAccountName: rampaz-server
      containers:
        - name: rampaz-server
          image: mujibahasan/rampaz-grpc:v1
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 50052
            - name: metrics
              containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi